<?php require ("template/header.phtml")?>

<div class="container-fluid">
  <div class="row">
    <div class="p-3 col-12 col-sm-6 col-lg-8">
	<div class="p-3 card card-cascade narrower">
<!--Card image-->
  <div
    class="view view-cascade gradient-card-header blue-gradient narrower py-2 mx-4 mb-3 d-flex justify-content-between align-items-center">

    <div>
      <button type="button" class="btn btn-outline-white btn-rounded btn-sm px-2">
        <i class="fas fa-th-large mt-0"></i>
      </button>
      <button type="button" class="btn btn-outline-white btn-rounded btn-sm px-2">
        <i class="fas fa-columns mt-0"></i>
      </button>
    </div>

    <div class="white-text mx-5">Current tickets</a></div>

    <div>
      <button type="button" class="btn btn-outline-white btn-rounded btn-sm px-2">
        <i class="fas fa-pencil-alt mt-0"></i>
      </button>
      <button type="button" class="btn btn-outline-white btn-rounded btn-sm px-2">
        <i class="far fa-trash-alt mt-0"></i>
      </button>
      <button type="button" class="btn btn-outline-white btn-rounded btn-sm px-2">
        <i class="fas fa-info-circle mt-0"></i>
      </button>
    </div>

  </div>
  <!--/Card image-->

<div class="table-responsive">
<form action="<?php echo $_SERVER['PHP_SELF']; ?>" method="post">
    <br>
    <table id="dtBasicExample" class="table table-hover">
       <thead>
        <tr><th>Post ID</th><th>Message</th><th>Reply Message</th><th>Status</th></tr>
       </thead>   
	<div class="card">
    <tbody> 
	<?php foreach ($view->postsDataSet as $postData) {
	echo '<tr>
		  <td>'. $postData->getPostID() .'</td>
		  <td>'. $postData->getMessage() . '</td>
		  <td>' . $postData->getReply() . '</td>
		  <td>' . $postData->getStatus() . '</td>
		  </tr>';
	}?>
	</div>
	</table>
	</div>
	</div>
	</div>
    <div class="p-5 col-6 col-lg-4">
	<!-- Material form contact -->
	<div class="card">

    <h5 class="card-header info-color white-text text-center py-4">
        <strong>Send a ticket</strong>
    </h5>

    <!--Card content-->
    <div class="card-body px-lg-5 pt-0">

        <!-- Form -->
        <form class="text-center" style="color: #757575;" action="ticket.php">
            <!--Message-->
            <div class="md-form">
                <textarea name="message" id="materialContactFormMessage" class="form-control md-textarea" rows="3"></textarea>
                <label for="materialContactFormMessage">Message</label>
            </div>

            <!-- Send button -->
            <button name="sendButton" class="btn btn-outline-info btn-rounded btn-block z-depth-0 my-4 waves-effect" type="submit">Send</button>

        </form>
        <!-- Form -->

    </div>

</div>
<!-- Material form contact -->
	</div>
  </div>
  </div>


<?php require ("template/footer.phtml")?>
<script>
$(document).ready(function () {
  $('#dtBasicExample').DataTable();
  $('.dataTables_length').addClass('bs-select');
});

// Material Select Initialization
$(document).ready(function() {
$('.mdb-select').materialSelect();
});
</script>