

      <link rel="stylesheet" type="text/css" href=""
      <footer class="page-footer bg-dark">
          <div class="bg-dark">
              <div class="footer-top">
                  <div class="container">

                      <div class="row py-4 d-flex align-items-center">

                          <div class="col-md-12 text-center">

                              <a href="#"><i class="fab fa-facebook-f text-white mr-4"></i></a>
                              <a href="#"><i class="fab fa-twitter text-white mr-4"></i></a>
                              <a href="#"><i class="fab fa-google-plus-g text-white mr-4"></i></a>
                              <a href="#"><i class="fab fa-linkedin-in text-white mr-4"></i></a>
                              <a href="#"><i class="fab fa-instagram text-white mr-4"></i></a>
                          </div>
                      </div>
                  </div>
              </div>
          </div>





      <div class="container text-center text-md-left mt-5">
          <div class="row">

              <div class="col-md-3 mx-auto mb-4">
                  <h6 class="text-uppercase font-weight-bold">Contact Us</h6>
                  <hr class="bg-dark mb-4 mt-0 d-inline-block mx-auto" style="width: 150px; height: 2px">
                  <h6 class="mt-2"> 078 8565 6342</h6>
                  <h6 class="mt-2"> 50 kings Lane</h6>
                  <h6 class="mt-2"> BL9 5AF</h6>
                  <h6 class="mt-2"> title@hotmail.com</h6>
              </div>


              <div class="col-md-3 mx-auto mb-4">
                  <h6 class="text-uppercase font-weight-bold">title</h6>
                  <hr class="bg-dark mb-4 mt-0 d-inline-block mx-auto" style="width: 150px; height: 2px">
                  <h6 class="mt-2"> About</h6>

                  <h6 class="mt-2"> Terms and Conditions</h6>
                  <h6 class="mt-2"> Privacy Policy</h6>
                  <h6 class="mt-2"> Cookies</h6>
                  <h6 class="mt-2"> Copyright © 2020 © 1995-2020 eBay Inc. All Rights Reserved.</h6>

              </div>
              <div class="col-md-2 mx-auto mb-4">
                  <h6 class="text-uppercase font-weight-bold">socials</h6>
                  <hr class="bg-dark mb-4 mt-0 d-inline-block mx-auto" style="width: 150px; height: 2px">

                  <ul class="list-unstyled">
                      <h6 class="mt-2"> </h6>
                      <h6 class="mt-2"> Facebook</h6>
                      <h6 class="mt-2"> Twiter</h6>
                      <h6 class="mt-2"> Instagram</h6>


                  </ul>
              </div>


          </div>
  </footer>



  <!-- SCRIPTS -->
  <!-- JQuery -->
    <!-- JQuery -->
  <script type="text/javascript" src="js/jquery-3.4.1.min.js"></script>
  <!-- Bootstrap tooltips -->
  <script type="text/javascript" src="js/popper.min.js"></script>
  <!-- Bootstrap core JavaScript -->
  <script type="text/javascript" src="js/bootstrap.min.js"></script>
  <!-- MDB core JavaScript -->
  <script type="text/javascript" src="js/mdb.min.js"></script>
  <!-- MDBootstrap Datatables  -->
  <script type="text/javascript" src="js/addons/datatables.min.js"></script>
</body>

</html>